# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: custom-script-py
        name: custom-script-py
        entry: python -m pre-commit-script
        language: python
        pass_filenames: false
        always_run: true
