name: Build and Deploy Code

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Check
        run: echo "Hello!"

      - name: Pull git repo
        uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

        steps:
        - uses: actions/checkout@v2
        - uses: FedericoCarboni/setup-ffmpeg@v1
          id: setup-ffmpeg
        - run: ffmpeg -i input.avi output.mkv

      - name: Test with Pytest
        run: pytest -k 'test_midi_generator or test_move_scale or test_scales' -v -s

      - name: Username
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/midi_auto_composer:latest
          


      