name: Build and Deploy Code

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v3
      - name: sanity check
        run: echo "Hello!"